<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VillagesSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $villages = [
            '10 miles',
            'Chalala',
            'Chamakulika',
            'Chankuwa',
            'Chanzanga',
            'Chayankkuwa',
            'Chayankuwa',
            'Chibebe',
            'Chibilika',
            'Chibilili',
            'Chiboshi',
            'Chibutu',
            'Chifumpa',
            'Chigwili',
            'Chikkunku',
            'Chikulumutwe',
            'Chikulumutwi',
            'Chikwesha',
            'Chikwili',
            'Chilete',
            'Chilikwela',
            'Chilimina',
            'Chilwana',
            'Chimbo',
            'Chinsanshi',
            'Chinsashi',
            'Chipalakasa',
            'Chipalaya',
            'Chipali',
            'Chipeso',
            'Chisanshi',
            'Chisashi',
            'Chisompola',
            'Chiyaba',
            'Chombela',
            'Choombela',
            'Green',
            'Kabongola',
            'Kabumbwe',
            'Kacha',
            'Kachusi',
            'Kadeke',
            'Kahinga',
            'Kakubo',
            'Kakuku',
            'Kalabo',
            'Kalobo',
            'Kalundomamwe',
            'Kalundu Mabwe',
            'Kalundumabwe',
            'Kambombo',
            'Kandeke',
            'Kandindima',
            'Kanyemba',
            'Kapila',
            'Kapila B',
            'Kapini',
            'Kapopo',
            'Kapowela',
            'Kapulumuma',
            'Kapulumuna',
            'Kasalu',
            'Kasapi',
            'Kaseba',
            'Kasheta',
            'Katalilo',
            'Kawele',
            'Kayuni',
            'Kwamachaya',
            'Lilanda',
            'Lubona',
            'Lubutwe',
            'Lukwalo',
            'Lupata',
            'Lupiya',
            'Luputa',
            'Lusaka',
            'Lyeempe',
            'Mabaya',
            'Machaya',
            'Makeni Villa Park',
            'Makusa',
            'Malaila',
            'Malakata',
            'Malanagilisha',
            'Malangilisha',
            'Malangisha',
            'Malupande',
            'Mankalo',
            'Mankalu',
            'Mankamba',
            'Mankhalo',
            'Manyama',
            'Mapili',
            'Mayaba',
            'Mbaimbai',
            'Meleki Musaika',
            'Meya',
            'Momba',
            'Moomba',
            'Mpandika',
            'Mpila',
            'Mpilika',
            'Muchenje',
            'Mukachilenga',
            'Mukubwanyama',
            'Mukumba',
            'Mukumbwanyama',
            'Mukuwa',
            'Mukwanga',
            'Mukwaya',
            'Mulaisho',
            'Mulimba',
            'Mulobela',
            'Mulobelo',
            'Mungule',
            'Mungule A',
            'Mungule B',
            'Mungule C',
            'Munkumba',
            'Munsongwe',
            'Muntemba',
            'Munthemba',
            'Mupaya',
            'Mupwaya',
            'Musaika',
            'Musakabantu',
            'Mushiko',
            'Musongwe',
            'Musumpuka',
            'Mutakwa',
            'Mutakwa B',
            'Mutakwa mwembeshi',
            'Mutakwa store',
            'Mutakwa village',
            'Mutakwamwembeshi',
            'Mutakwasto',
            'Mutakwastore',
            'Mutemba',
            'Mutemba Mutakwa',
            'Mutokoma',
            'Muyupi',
            'Mwachibutu',
            'Mwachifumpa',
            'Mwachifumpwa',
            'Mwachikoka',
            'Mwachikonkonto',
            'Mwachinondo',
            'Mwachipalaya',
            'Mwakakwela',
            'Mwakakwele',
            'Mwakambombo',
            'Mwakawele',
            'Mwalewanika',
            'Mwalilanda',
            'Mwalukwanda',
            'Mwaluputa',
            'Mwalusaka',
            'Mwamulowa',
            'Mwansakila',
            'Mwansakilwa',
            'Mwashingwele',
            'Mwembeshi-land',
            'mwembeshiland',
            'Namanja',
            'Ndalama',
            'Nkaba',
            'Nselegwe',
            'Nselengwe',
            'Nshikuku',
            'Nshikunku',
            'Nshilima',
            'Nyeleti',
            'Pwalakasa',
            'Saile',
            'Saili',
            'Selengwa',
            'Selengwe',
            'Shaamakulika',
            'Shabafwa',
            'Shabwaafwa',
            'Shabwafa',
            'Shabwafwa',
            'Shafuluma',
            'Shalutubya',
            'Shamakulika',
            'Shamboko',
            'Shamutuku',
            'Shamwenda',
            'Shamwinda',
            'Shandyongo',
            'Shibuyunji',
            'Shikunku',
            'Shikwesha',
            'Shilima',
            'Shimalosa',
            'Shimalosha',
            'Shimalungwe',
            'Shimukuni',
            'Shinkunku',
            'Sibuyunji',
            'vILAGE',
            'WoodLands',
        ];

        $rows = array_map(static fn (string $name): array => [
            'name' => $name,
            'created_at' => $now,
            'updated_at' => $now,
        ], $villages);

        foreach (array_chunk($rows, 200) as $chunk) {
            DB::table('villages')->upsert($chunk, ['name'], ['updated_at']);
        }

        $this->command?->info('Seeded ' . count($villages) . ' villages.');
    }
}
